Write a Python Program to Add Two Matrices?

In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]);
b= np.array([[4,5,6],[7,8,9],[1,2,3]]);
c=a+b
print(c)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


Write a Python Program to Multiply Two Matrices?

In [2]:
c=a*b
print(c)

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]


Write a Python Program to Transpose a Matrix?

In [3]:
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
a=['b','e','a','c','h']
a.sort()
print(a)

['a', 'b', 'c', 'e', 'h']


Write a Python Program to Remove Punctuation From a String?

In [5]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
st = "..!@<>He..!@<>llo The..!@<>re..!@<>";
new_st='';
for i in st:
    if i not in punctuations:
        new_st+=i;
print(new_st)

Hello There
